project:
  type: website

website:
  title: "NFL Combine Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Running Backs.qmd
      - Wide Receivers.qmd
      - Tight Ends.qmd
      - Cornerbacks.qmd
      - Safeties.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

