---
title: "Safeties"
execute:
  echo: false
  warning: false
  message: false
---

```{r}
library(leaflet)
library(tidyverse)
library(nflverse)
library(ggplot2)
tribble1 <- tribble(~position,~Player,~yarddash,~vertical,~bench,
                    "Safety", "Antoine \nWinfield", 4.45, 36, NA,
                    "Safety", "Kyle \nHamilton", 4.59, 38, NA,
                    "Safety", "Jessie \nBates III", 4.5, 35.5, 12,
                    "Safety", "Minkah \nFitzpatrick", 4.46, 33, 14,
                    "Safety", "Marcus \nWilliams", 4.56, 33, 14,
                    "Safety", "League \nAverage", 4.54, 36.22, 17.195,
                    "Cornerback", "Sauce \nGardner", 4.41, NA, NA,
                    "Cornerback", "Trent \nMcDuffie", 4.44, 38.5, 15,
                    "Cornerback","Charavius \nWard", 4.44, 31, 12,
                    "Cornerback","Pat \nSurtain II", 4.46, 39, 18,
                    "Cornerback", "Jaylon \nJohnson", 4.5, 36.5, 15,
                    "Cornerback", "League \nAverage", 4.48, 36.26, 14.94,
                    "Wide Receiver", "Justin \nJefferson", 4.43, 37.5, NA,
                    "Wide Receiver","Tyreek \nHill", 4.29, 40.5, 13,
                    "Wide Receiver", "Ja'Marr \nChase", 4.38, 41, 23,
                    "Wide Receiver", "CeeDee \nLamb", 4.51, 34.5, 11,
                    "Wide Receiver", "AJ \nBrown", 4.49, 36.5, 19,
                    "Wide Receiver", "League \nAverage", 4.48, 35.84, 15.21,
                    "Tight End", "George \nKittle", 4.52, 38.5, 18,
                    "Tight End", "Travis \nKelce", 4.61, 35, NA,
                    "Tight End", "Mark \nAndrews", 4.67, 31, 17,
                    "Tight End", "TJ \nHockenson", 4.7, 37.5, 17,
                    "Tight End", "Sam \nLaPorta", 4.59, 35, 16,
                    "Tight End", "League \nAverage", 4.7, 33.47, 21.53, 
                    "Running Back", "Christian \nMcCaffrey", 4.48, 37.5, 10,
                    "Running Back", "Derrick \nHenry", 4.54, 37, 22,
                    "Running Back", "Jonathan \nTaylor", 4.39, 36, 17,
                    "Running Back", "Nick \nChubb", 4.52, 38.5, 29,
                    "Running Back","Bijan \nRobinson", 4.46, 37, NA,
                    "Running Back","League \nAverage", 4.49, 35.1, 20.43)
```

```{r}
tribble1|>filter(position == "Safety")|>ggplot(aes(tribble1,x = Player, y = yarddash))+
geom_col(aes(fill = Player))+
  coord_cartesian(ylim = c(4,4.7))+
  theme_minimal()+
  labs(title = "40 Yard Dash Times (seconds) of Top 5 NFL Safeties vs League Average",subtitle = "3 out of 5 of the top 5 NFL safeties had a better 40 yard dash time than the league average.", x = "Player",y = "Time (Seconds)")

tribble1|>drop_na()|>filter(position == "Safety")|>ggplot(aes(tribble1,x = Player, y = vertical))+
geom_col(aes(fill = Player))+
  coord_cartesian(ylim = c(20,41))+
  theme_minimal()+
  labs(title = "Vertical Jump Heights (inches) of Top 5 NFL Safeties vs League Average",subtitle = "All 3 safeties who did the vertical jump at the combine had a worse vertical jump than the league average", x = "Player",y = "Vertical Jump(Inches)")

tribble1|>drop_na()|>filter(position == "Safety")|>ggplot(aes(tribble1,x = Player, y = bench))+
geom_col(aes(fill = Player))+
  coord_cartesian(ylim = c(0,30))+
  theme_minimal()+
  labs(title = "Bench Presses (reps of 225 lbs) of Top 5 NFL Safeties vs League Average",subtitle =  "Again, all three of the top 5 safeties in the NFL had less bench press reps than the league average.", x = "Player",y = "Bench Press(Reps of 225)")
```
